
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pinpag-banking_app
    ports:
      - "5000:8000"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=YourDatabase;Username=youruser;Password=yourpassword
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: pinpag-banking_db
    restart: always
    environment:
      POSTGRES_DB: YourDatabase
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
